let originalImage=null,pixelData=null,stitchData=null,usedColors=[],totalStitches=0;
function loadImage(input){const file=input.files[0];if(!file)return;if(!file.type.startsWith('image/')){showToast('⚠ الرجاء اختيار صورة');return}const reader=new FileReader();reader.onload=function(e){const img=new Image();img.onload=function(){originalImage=img;showEditor();processImage()};img.src=e.target.result};reader.readAsDataURL(file)}
function loadSample(type){const canvases={flower:drawFlower,heart:drawHeart,star:drawStar,cat:drawCat};if(canvases[type]){const c=document.createElement('canvas');c.width=200;c.height=200;canvases[type](c.getContext('2d'));const img=new Image();img.onload=function(){originalImage=img;showEditor();processImage()};img.src=c.toDataURL()}}
function drawFlower(ctx){ctx.fillStyle='#FF69B4';ctx.beginPath();for(let i=0;i<5;i++){const a=i*Math.PI*0.8;ctx.ellipse(100,80,30,15,a,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#FFD700';ctx.beginPath();ctx.arc(100,100,20,0,Math.PI*2);ctx.fill()}
function drawHeart(ctx){ctx.fillStyle='#FF0000';ctx.beginPath();ctx.moveTo(100,150);ctx.bezierCurveTo(0,90,0,20,60,20);ctx.bezierCurveTo(100,20,100,60,100,60);ctx.bezierCurveTo(100,60,100,20,140,20);ctx.bezierCurveTo(200,20,200,90,100,150);ctx.fill()}
function drawStar(ctx){ctx.fillStyle='#FFD700';ctx.beginPath();for(let i=0;i<5;i++){const a=i*Math.PI*0.8-Math.PI/2;const r=i%2===0?80:35;const x=100+Math.cos(a)*r,y=100+Math.sin(a)*r;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath();ctx.fill()}
function drawCat(ctx){ctx.fillStyle='#FFA500';ctx.beginPath();ctx.arc(100,100,60,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(70,85,12,0,Math.PI*2);ctx.arc(130,85,12,0,Math.PI*2);ctx.fillStyle='#000';ctx.fill();ctx.beginPath();ctx.arc(100,120,8,0,Math.PI);ctx.strokeStyle='#000';ctx.lineWidth=2;ctx.stroke()}
function showEditor(){document.getElementById('uploadSection').style.display='none';document.getElementById('editorSection').style.display='block'}
function resetEditor(){document.getElementById('uploadSection').style.display='block';document.getElementById('editorSection').style.display='none';originalImage=null}
function processImage(){showLoading();setTimeout(()=>{const gs=parseInt(document.getElementById('gridSize').value);const mc=parseInt(document.getElementById('maxColors').value);pixelData=pixelate(originalImage,gs);stitchData=quantizeColors(pixelData,mc);renderStitch();updateColorChart();hideLoading()},300)}
function pixelate(img,size){const c=document.createElement('canvas');const ratio=Math.min(size/img.width,size/img.height);c.width=Math.floor(img.width*ratio);c.height=Math.floor(img.height*ratio);const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);return ctx.getImageData(0,0,c.width,c.height)}
function quantizeColors(imageData,maxColors){const pixels=[];for(let i=0;i<imageData.data.length;i+=4){pixels.push([imageData.data[i],imageData.data[i+1],imageData.data[i+2]])}const colorMap={};pixels.forEach(p=>{const c=findClosestColor(p[0],p[1],p[2]);const key=c.code;if(!colorMap[key])colorMap[key]={color:c,count:0};colorMap[key].count++});const sorted=Object.values(colorMap).sort((a,b)=>b.count-a.count).slice(0,maxColors);usedColors=sorted.map(s=>s.color);totalStitches=pixels.length;const quantized=[];pixels.forEach(p=>{const c=findClosestInList(p[0],p[1],p[2],usedColors);quantized.push(c)});return {width:imageData.width,height:imageData.height,data:quantized}}
function findClosestInList(r,g,b,list){let minDist=Infinity,closest=list[0];list.forEach(c=>{const dr=r-c.rgb[0],dg=g-c.rgb[1],db=b-c.rgb[2];const dist=dr*dr+dg*dg+db*db;if(dist<minDist){minDist=dist;closest=c}});return closest}
function updateGrid(){if(originalImage)processImage()}