let currentFreq=87.5,isRadioOn=false,fmRadio=null,tuneInterval=null,isScanning=false,cancelScanFlag=false;
function initFMRadio(){currentFreq=getLastFreq();document.getElementById('freqDisplay').innerText=currentFreq.toFixed(1);checkHeadphones();updateSignalBars();updateSavedStations()}
function checkHeadphones(){if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){navigator.mediaDevices.enumerateDevices().then(devices=>{const hasHeadphone=devices.some(d=>d.kind==='audiooutput'&&(d.deviceId!=='default'&&d.deviceId!=='communications'));if(!hasHeadphone){document.getElementById('headphoneAlert').style.display='flex'}else{document.getElementById('headphoneAlert').style.display='none'}}).catch(()=>{})}else{document.getElementById('headphoneAlert').style.display='flex'}}
function toggleRadio(){if(isRadioOn){turnOffRadio()}else{turnOnRadio()}}
function turnOnRadio(){isRadioOn=true;document.body.classList.add('playing');document.body.classList.remove('paused');document.getElementById('playIcon').className='fas fa-power-off';document.getElementById('statusDot').style.background='#22c55e';document.getElementById('stationSignal').innerText='📶 FM '+currentFreq.toFixed(1)+' MHz';updateSignalBars();showToast('📻 تم تشغيل الراديو')}
function turnOffRadio(){isRadioOn=false;document.body.classList.remove('playing');document.body.classList.add('paused');document.getElementById('playIcon').className='fas fa-power-off';document.getElementById('statusDot').style.background='#ef4444';document.getElementById('stationSignal').innerText='📻 الراديو متوقف';updateSignalBars();showToast('📻 تم إيقاف الراديو')}
function tuneUp(){currentFreq=Math.min(108.0,currentFreq+0.1);updateFreqDisplay();if(isRadioOn)tuneToStation()}
function tuneDown(){currentFreq=Math.max(87.5,currentFreq-0.1);updateFreqDisplay();if(isRadioOn)tuneToStation()}
function startTune(dir){tuneInterval=setInterval(()=>{dir==='up'?tuneUp():tuneDown()},150)}
function stopTune(){if(tuneInterval){clearInterval(tuneInterval);tuneInterval=null;if(isRadioOn)showToast('📻 '+currentFreq.toFixed(1)+' MHz')}}
function seekUp(){let f=currentFreq+0.1;while(f<=108.0){if(isFavoriteFreq(parseFloat(f.toFixed(1)))){currentFreq=f;updateFreqDisplay();if(isRadioOn)tuneToStation();showToast('📻 وجدت محطة: '+currentFreq.toFixed(1)+' MHz');return}f+=0.1}showToast('⚠ لا توجد محطات محفوظة تالية')}
function seekDown(){let f=currentFreq-0.1;while(f>=87.5){if(isFavoriteFreq(parseFloat(f.toFixed(1)))){currentFreq=f;updateFreqDisplay();if(isRadioOn)tuneToStation();showToast('📻 وجدت محطة: '+currentFreq.toFixed(1)+' MHz');return}f-=0.1}showToast('⚠ لا توجد محطات محفوظة سابقة')}
function autoScan(){if(isScanning)return;isScanning=true;cancelScanFlag=false;document.getElementById('scanOverlay').classList.add('show');document.getElementById('scanFill').style.width='0%';scanStep(87.5)}
function scanStep(freq){if(cancelScanFlag||freq>108.0){finishScan();return}currentFreq=freq;updateFreqDisplay();document.getElementById('scanFreq').innerText=freq.toFixed(1)+' MHz';const progress=((freq-87.5)/(108.0-87.5))*100;document.getElementById('scanFill').style.width=progress+'%';setTimeout(()=>{if(isFavoriteFreq(parseFloat(freq.toFixed(1)))){addFavorite('FM '+freq.toFixed(1),parseFloat(freq.toFixed(1)));showToast('📻 وجدت محطة: '+freq.toFixed(1)+' MHz')}scanStep(freq+0.1)},80)}
function finishScan(){isScanning=false;document.getElementById('scanOverlay').classList.remove('show');updateSavedStations();if(!cancelScanFlag)showToast('✅ اكتمل المسح التلقائي')}
function cancelScan(){cancelScanFlag=true;finishScan()}
function tuneToStation(){saveLastFreq(currentFreq);document.getElementById('stationSignal').innerText='📶 FM '+currentFreq.toFixed(1)+' MHz';updateSignalBars()}
function updateFreqDisplay(){document.getElementById('freqDisplay').innerText=currentFreq.toFixed(1);saveLastFreq(currentFreq);updateFavBtn()}
function updateSignalBars(){const strength=isRadioOn?Math.floor(Math.random()*3)+3:0;for(let i=1;i<=5;i++){const bar=document.getElementById('sig'+i);if(bar)bar.classList.toggle('active',i<=strength)}}
function toggleFavorite(){const freq=parseFloat(currentFreq.toFixed(1));if(isFavoriteFreq(freq)){removeFavorite(freq);showToast('🗑 تم حذف المحطة')}else{const name=prompt('اسم المحطة:','FM '+freq.toFixed(1));if(name){addFavorite(name,freq);showToast('⭐ تم حفظ المحطة')}}updateFavBtn();updateSavedStations()}
function updateFavBtn(){const freq=parseFloat(currentFreq.toFixed(1));const btn=document.getElementById('favBtn');const icon=document.getElementById('favIcon');btn.classList.toggle('active',isFavoriteFreq(freq));icon.className=isFavoriteFreq(freq)?'fas fa-star':'far fa-star'}
function updateSavedStations(){const container=document.getElementById('savedStations');const favs=getFavorites();if(!favs.length){container.innerHTML='<div class="empty-state"><span class="empty-icon">📻</span><p>لا توجد محطات محفوظة</p><span style="font-size:9px;color:var(--text3)">اضغط ⭐ لحفظ المحطة الحالية</span></div>';return}container.innerHTML=favs.map((s,i)=>{const active=Math.abs(s.freq-currentFreq)<0.05?'active':'';return`<div class="saved-item ${active}" onclick="tuneToSaved(${s.freq})"><div class="saved-info"><span class="saved-freq">${s.freq.toFixed(1)}</span><span class="saved-name">${s.name}</span></div><button class="saved-del" onclick="event.stopPropagation();deleteSaved(${s.freq})"><i class="fas fa-trash"></i></button></div>`}).join('')}
function tuneToSaved(freq){currentFreq=freq;updateFreqDisplay();if(isRadioOn)tuneToStation();showToast('📻 '+freq.toFixed(1)+' MHz')}
function deleteSaved(freq){removeFavorite(freq);updateFavBtn();updateSavedStations();showToast('🗑 تم الحذف')}
function setVolume(v){if(fmRadio&&fmRadio.setVolume)fmRadio.setVolume(v/100);saveVolume(v)}
function showSavedStations(){updateSavedStations()}