function renderGallery(){const grid=document.getElementById('galleryGrid');const items=getGallery();if(!items.length){grid.innerHTML='<div class="empty-gallery"><div class="empty-icon">🖼️</div><p>المعرض فارغ</p><span>ابدأ بتوليد الصور لإضافتها هنا</span></div>';return}grid.innerHTML=items.map((item,i)=>`<div class="gallery-item" onclick="previewImage(${i})"><img src="${item.data}" alt="Art"><div class="item-date">${item.date||''}</div></div>`).join('')}
function saveToGallery(){if(!window.currentGeneratedImage){showToast('⚠ لا توجد صورة للحفظ');return}addToGallery(window.currentGeneratedImage,window.currentPrompt||'',window.currentStyle||'');switchTab('gallery');renderGallery();showToast('💾 تم الحفظ في المعرض')}
function previewImage(index){const items=getGallery();if(index>=items.length)return;const item=items[index];document.getElementById('modalImage').src=item.data;document.getElementById('modalOverlay').classList.add('show');window.currentModalIndex=index}
function closeModal(){document.getElementById('modalOverlay').classList.remove('show')}
function downloadModalImage(){const img=document.getElementById('modalImage');const a=document.createElement('a');a.href=img.src;a.download='ai-art-2044.png';a.click()}
function shareModalImage(){if(navigator.share){const img=document.getElementById('modalImage');fetch(img.src).then(r=>r.blob()).then(b=>{navigator.share({title:'AI Art Studio 2044',files:[new File([b],'art.png',{type:'image/png'})]})}).catch(()=>{})}else{showToast('📤 انسخ الصورة وشاركها')}}
function deleteModalImage(){if(window.currentModalIndex!==undefined){const items=getGallery();if(items[window.currentModalIndex]){removeFromGallery(items[window.currentModalIndex].id);closeModal();renderGallery();showToast('🗑 تم الحذف')}}}
function downloadImage(){if(!window.currentGeneratedImage)return;const a=document.createElement('a');a.href=window.currentGeneratedImage;a.download='ai-art-2044.png';a.click();showToast('📥 تم التحميل')}
function shareImage(){if(navigator.share&&window.currentGeneratedImage){fetch(window.currentGeneratedImage).then(r=>r.blob()).then(b=>{navigator.share({title:'AI Art Studio 2044',files:[new File([b],'art.png',{type:'image/png'})]})}).catch(()=>{})}else{showToast('📤 انسخ الصورة وشاركها')}}
function addFilters(){if(!window.currentGeneratedImage)return;const img=new Image();img.onload=function(){filterImage=img;document.getElementById('filterPreview').style.display='block';filterCanvas=document.getElementById('filterCanvas');filterCtx=filterCanvas.getContext('2d');switchTab('filters');applyFilter('none')};img.src=window.currentGeneratedImage}