let audio=new Audio(),playlist=[],currentIndex=-1,isPlaying=false,isShuffle=false,isRepeat=false,audioCtx=null,analyser=null;
function initPlayer(){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();analyser=audioCtx.createAnalyser();analyser.fftSize=256;const source=audioCtx.createMediaElementSource(audio);source.connect(analyser);analyser.connect(audioCtx.destination)}catch(e){console.log('AudioContext not supported')}playlist=loadPlaylist();renderPlaylist();if(playlist.length){loadTrack(0)}audio.addEventListener('timeupdate',onTimeUpdate);audio.addEventListener('ended',()=>isRepeat?audio.play():nextTrack());audio.addEventListener('play',()=>{isPlaying=true;document.getElementById('playIcon').className='fas fa-pause'});audio.addEventListener('pause',()=>{isPlaying=false;document.getElementById('playIcon').className='fas fa-play'})}
function onTimeUpdate(){if(!audio.duration)return;const pct=(audio.currentTime/audio.duration)*100;document.getElementById('progressFill').style.width=pct+'%';document.getElementById('progressThumb').style.left=pct+'%';document.getElementById('currentTime').innerText=formatTime(audio.currentTime);document.getElementById('totalTime').innerText=formatTime(audio.duration);updateLyricPosition(audio.currentTime);if(analyser){const data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(data);updateVizData(data)}}
function formatTime(s){const m=Math.floor(s/60),sec=Math.floor(s%60);return m+':'+(sec<10?'0':'')+sec}
function loadTrack(i){if(i<0||i>=playlist.length)return;currentIndex=i;window.currentTrack=playlist[i];const t=playlist[i];audio.src=t.data;document.getElementById('trackTitle').innerText=t.name;document.getElementById('trackArtist').innerText=t.size;loadTrackLyrics(t.id);renderPlaylist();audio.play()}
function togglePlay(){if(!audio.src&&playlist.length){loadTrack(0);return}isPlaying?audio.pause():audio.play()}
function nextTrack(){if(!playlist.length)return;let n=isShuffle?Math.floor(Math.random()*playlist.length):currentIndex+1;if(n>=playlist.length)n=0;loadTrack(n)}
function prevTrack(){if(!playlist.length)return;let p=currentIndex-1;if(p<0)p=playlist.length-1;loadTrack(p)}
function toggleShuffle(){isShuffle=!isShuffle;document.getElementById('shuffleBtn').classList.toggle('active',isShuffle)}
function toggleRepeat(){isRepeat=!isRepeat;document.getElementById('repeatBtn').classList.toggle('active',isRepeat)}
function seek(e){if(!audio.duration)return;const r=document.getElementById('progressTrack').getBoundingClientRect();audio.currentTime=((e.clientX-r.left)/r.width)*audio.duration}
function addFiles(input){const files=input.files;if(!files.length)return;Array.from(files).forEach(f=>{const r=new FileReader();r.onload=function(e){playlist.push({id:Date.now()+Math.random(),name:f.name.replace(/\.[^/.]+$/,''),size:formatSize(f.size),data:e.target.result,addedAt:new Date().toISOString()});savePlaylist(playlist);renderPlaylist();if(playlist.length===1)loadTrack(0)};r.readAsDataURL(f)});input.value='';showToast('✅ '+files.length+' أغنية')}
function formatSize(b){return b>1048576?(b/1048576).toFixed(1)+' MB':(b/1024).toFixed(1)+' KB'}
function deleteTrack(i){const wasPlaying=currentIndex===i;playlist.splice(i,1);savePlaylist(playlist);if(wasPlaying){audio.pause();audio.src='';document.getElementById('trackTitle').innerText='اختر أغنية';document.getElementById('trackArtist').innerText='Sonic 2044';isPlaying=false;document.getElementById('playIcon').className='fas fa-play';currentIndex=-1}else if(currentIndex>i)currentIndex--;renderPlaylist();showToast('🗑 تم الحذف')}
function renderPlaylist(){const c=document.getElementById('playlist');if(!playlist.length){c.innerHTML='<div class="empty-playlist"><span>🎵</span><p>اسحب ملفات الصوت هنا</p></div>';return}c.innerHTML=playlist.map((t,i)=>`<div class="track-item ${i===currentIndex?'active':''}" onclick="loadTrack(${i})"><div class="t-icon">${i===currentIndex&&isPlaying?'🔊':'🎵'}</div><div class="t-info"><div class="t-name">${t.name}</div><div class="t-size">${t.size}</div></div><span class="t-del" onclick="event.stopPropagation();deleteTrack(${i})"><i class="fas fa-trash"></i></span></div>`).join('')}
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}