let zoom=1,offsetX=0,offsetY=0;
function renderStitch(){if(!stitchData)return;const canvas=document.getElementById('stitchCanvas');const gs=parseInt(document.getElementById('gridSize').value);const st=document.getElementById('stitchType').value;const size=Math.min(400,window.innerWidth-60);canvas.width=stitchData.width*zoom;canvas.height=stitchData.height*zoom;canvas.style.width=Math.min(stitchData.width*zoom,size)+'px';const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;const cellW=canvas.width/stitchData.width;const cellH=canvas.height/stitchData.height;for(let y=0;y<stitchData.height;y++){for(let x=0;x<stitchData.width;x++){const idx=y*stitchData.width+x;const color=stitchData.data[idx];if(!color)continue;const px=x*cellW,py=y*cellH;ctx.fillStyle=color.hex;if(st==='full'){drawFullStitch(ctx,px,py,cellW,cellH,color)}else if(st==='half'){drawHalfStitch(ctx,px,py,cellW,cellH,color)}else{ctx.fillRect(px,py,cellW,cellH)}}}drawGridLines(ctx,cellW,cellH)}
function drawFullStitch(ctx,x,y,w,h,color){const darker=darkenColor(color.hex,0.3);ctx.fillStyle=color.hex;ctx.fillRect(x,y,w,h);ctx.strokeStyle=darker;ctx.lineWidth=0.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y+h);ctx.moveTo(x+w,y);ctx.lineTo(x,y+h);ctx.stroke()}
function drawHalfStitch(ctx,x,y,w,h,color){const darker=darkenColor(color.hex,0.3);ctx.fillStyle=color.hex;ctx.fillRect(x,y,w,h);ctx.strokeStyle=darker;ctx.lineWidth=0.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y+h);ctx.stroke()}
function drawGridLines(ctx,cw,ch){ctx.strokeStyle='rgba(255,255,255,0.08)';ctx.lineWidth=0.5;for(let x=0;x<=stitchData.width;x++){ctx.beginPath();ctx.moveTo(x*cw,0);ctx.lineTo(x*cw,stitchData.height*ch);ctx.stroke()}for(let y=0;y<=stitchData.height;y++){ctx.beginPath();ctx.moveTo(0,y*ch);ctx.lineTo(stitchData.width*cw,y*ch);ctx.stroke()}}
function darkenColor(hex,amount){const num=parseInt(hex.replace('#',''),16);const r=Math.max(0,Math.floor((num>>16)* (1-amount)));const g=Math.max(0,Math.floor(((num>>8)&0xFF)*(1-amount)));const b=Math.max(0,Math.floor((num&0xFF)*(1-amount)));return '#'+(r<<16|g<<8|b).toString(16).padStart(6,'0')}
function updateColorChart(){const chart=document.getElementById('colorChart');chart.innerHTML=usedColors.map(c=>`<div class="color-chip"><div class="color-swatch" style="background:${c.hex}"></div><span>DMC ${c.code}</span><span style="color:rgba(255,255,255,0.4)">${c.name}</span></div>`).join('');document.getElementById('totalStitches').innerText=totalStitches;document.getElementById('colorCount').innerText=usedColors.length}
function zoomIn(){zoom=Math.min(zoom*1.5,10);updateZoomDisplay();renderStitch()}
function zoomOut(){zoom=Math.max(zoom/1.5,0.5);updateZoomDisplay();renderStitch()}
function resetZoom(){zoom=1;updateZoomDisplay();renderStitch()}
function updateZoomDisplay(){document.getElementById('zoomLevel').innerText=Math.round(zoom*100)+'%'}