let canvas,ctx,gs=16,ts,snake=[],dir={x:1,y:0},nd={x:1,y:0},food=null,ft=null,score=0,combo=1,ir=false,ip=false,ig=false,gl=null,sp=140,gc=0,pf=0,sc_=0,bs=0,eatEffects=[],shakeAmount=0;

function ig_(){canvas=document.getElementById('gameCanvas');ctx=canvas.getContext('2d');rc_();window.addEventListener('resize',rc_);initParticles();initAudio();bs=getBestScore();document.getElementById('bestDisplay').innerText=bs;stfs_();di_();sk_();const s=loadSettings();soundEnabled=s.sound!==false;document.getElementById('soundBtn').classList.toggle('active',!soundEnabled)}

function rc_(){const c=canvas.parentElement;const mw=c.clientWidth-20;const mh=c.clientHeight-20;const s=Math.min(mw,mh,400);canvas.width=s;canvas.height=s;ts=s/gs;if(!ir)di_()}

function sk_(){document.addEventListener('keydown',e=>{if(!ir||ip)return;switch(e.key){case'ArrowUp':case'w':case'W':cd_(0,-1);break;case'ArrowDown':case's':case'S':cd_(0,1);break;case'ArrowLeft':case'a':case'A':cd_(-1,0);break;case'ArrowRight':case'd':case'D':cd_(1,0);break;case' ':e.preventDefault();tp_();break}})}

function cd_(dx,dy){if(!ir||ip)return;if(dx===0&&dir.y===0)nd={x:dx,y:dy};if(dy===0&&dir.x===0)nd={x:dx,y:dy}}

function stfs_(){const s=loadSettings();currentTheme=s.theme||'neon';ig=s.ghost||false;if(ig)document.getElementById('ghostBtn').classList.add('active');updateBackground();updateParticles()}

function updateBackground(){const t=getTheme();document.getElementById('bgMesh').style.background=`conic-gradient(from 0deg at 50% 50%,${t.bg} 0%,${t.bg2} 25%,${t.bg} 50%,${t.bg2} 75%,${t.bg} 100%)`;document.getElementById('bgOrb1').style.background=t.orb1;document.getElementById('bgOrb2').style.background=t.orb2;document.getElementById('bgOrb3').style.background=t.orb3;document.getElementById('themeBadge').innerText='✨ '+t.name;document.getElementById('themeBadge').style.color=t.accent;document.getElementById('themeBadge').style.borderColor=t.accent;document.getElementById('themeBadge').style.background=t.accent.replace(')','.1)')}

function changeTheme(){const ts_=Object.keys(THEMES);const i=ts_.indexOf(currentTheme);currentTheme=ts_[(i+1)%ts_.length];saveSettings({theme:currentTheme,ghost:ig,sound:soundEnabled});updateBackground();updateParticles();showToast('🎨 '+getTheme().name);if(!ir)di_();const tried=loadSettings().triedThemes||[];if(!tried.includes(currentTheme)){tried.push(currentTheme);const s=loadSettings();s.triedThemes=tried;saveSettings(s)}if(Object.keys(THEMES).every(t=>currentTheme===t||tried.includes(t))){if(unlockAchievement('all_themes')){showToast('🎨 فنان! كل الثيمات!')}}}

function toggleGhost(){ig=!ig;saveSettings({theme:currentTheme,ghost:ig,sound:soundEnabled});document.getElementById('ghostBtn').classList.toggle('active',ig);showToast(ig?'👻 وضع الشبح مفعل':'👻 وضع الشبح ملغي')}

function di_(){const t=getTheme();ctx.fillStyle=t.bg;ctx.fillRect(0,0,canvas.width,canvas.height);dg_();ctx.fillStyle=t.snake;const cx=Math.floor(gs/2);const cy=Math.floor(gs/2);for(let i=0;i<5;i++){ctx.fillRect((cx+i)*ts+1,cy*ts+1,ts-2,ts-2)}ctx.fillStyle=t.food;ctx.shadowColor=t.foodGlow;ctx.shadowBlur=20;ctx.beginPath();ctx.arc((cx-2)*ts+ts/2,cy*ts+ts/2,ts/2-2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}

function startGame(){snake=[{x:Math.floor(gs/2),y:Math.floor(gs/2)}];dir={x:1,y:0};nd={x:1,y:0};score=0;combo=1;sp=getSpeed();gc=0;pf=0;sc_=0;eatEffects=[];shakeAmount=0;obstacles=spawnObstacles(gs);currentLevel=0;sf_();ir=true;ip=false;document.getElementById('gameOverlay').style.display='none';document.getElementById('scoreDisplay').innerText='0';document.getElementById('levelDisplay').innerText='1';document.getElementById('comboDisplay').innerText='x1';document.getElementById('comboDisplay').style.color='#ffaa00';if(gl)clearInterval(gl);gl=setInterval(up_,sp);unlockAchievement('first_game')}

function sf_(){let p;do{p={x:Math.floor(Math.random()*gs),y:Math.floor(Math.random()*gs)}}while(snake.some(s=>s.x===p.x&&s.y===p.y)||checkObstacle(p.x,p.y));food=p;ft=getRandomFruit()}

function up_(){if(!ir||ip)return;dir={...nd};const h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(!ig){if(h.x<0||h.x>=gs||h.y<0||h.y>=gs)return die_();if(snake.some(s=>s.x===h.x&&s.y===h.y))return die_();if(checkObstacle(h.x,h.y)){shakeAmount=10;return die_()}}else{if(h.x<0)h.x=gs-1;if(h.x>=gs)h.x=0;if(h.y<0)h.y=gs-1;if(h.y>=gs)h.y=0}snake.unshift(h);if(h.x===food.x&&h.y===food.y){const p=ft.points*Math.max(1,Math.floor(combo));score+=Math.max(0,p);eatEffects.push({x:food.x,y:food.y,life:1,color:ft.glow||ft.color});if(ft.type==='golden'){gc++;playGolden()}else if(ft.type==='speed'){sc_++;sp=Math.max(32,sp-10);clearInterval(gl);gl=setInterval(up_,sp);playEat()}else if(ft.type==='slow'){sp+=6;clearInterval(gl);gl=setInterval(up_,sp);playEat()}else if(ft.type==='poison'){combo=1;playDie()}else{pf++;playEat()}if(ft.type!=='poison'){combo=Math.min(combo+1,25);if(combo>=5&&combo%5===0){const cp=document.getElementById('comboPopup');cp.textContent='🔥 x'+Math.floor(combo);cp.classList.add('show');setTimeout(()=>cp.classList.remove('show'),600)}}if(combo>=10)document.getElementById('comboDisplay').style.color='#ff4444';else if(combo>=5)document.getElementById('comboDisplay').style.color='#ffaa00';else document.getElementById('comboDisplay').style.color='#ffaa00';checkScoreAchievements(score,gc,currentLevel+1,Math.floor(combo),pf,sc_);if(score>=getRequired()&&currentLevel<LEVELS.length-1){currentLevel++;sp=getSpeed();clearInterval(gl);gl=setInterval(up_,sp);obstacles=spawnObstacles(gs);playLevelUp();showToast('🎉 '+LEVELS[currentLevel].name+'!')}sf_()}else{snake.pop();combo=Math.max(1,combo-0.03);if(combo<3)document.getElementById('comboDisplay').style.color='#ffaa00'}eatEffects=eatEffects.filter(e=>{e.life-=0.05;return e.life>0});if(shakeAmount>0)shakeAmount*=0.85;uu_();dr_()}

function uu_(){document.getElementById('scoreDisplay').innerText=score;document.getElementById('levelDisplay').innerText=currentLevel+1;document.getElementById('comboDisplay').innerText='x'+Math.floor(combo);if(score>bs){bs=score;document.getElementById('bestDisplay').innerText=bs}}

function dr_(){const t=getTheme();ctx.save();if(shakeAmount>0.5){const sx=(Math.random()-0.5)*shakeAmount;const sy=(Math.random()-0.5)*shakeAmount;ctx.translate(sx,sy)}ctx.fillStyle=t.bg;ctx.fillRect(0,0,canvas.width,canvas.height);dg_();obstacles.forEach(o=>{ctx.fillStyle='rgba(255,255,255,0.06)';ctx.shadowColor='rgba(255,0,0,0.3)';ctx.shadowBlur=5;ctx.fillRect(o.x*ts+2,o.y*ts+2,ts-4,ts-4);ctx.shadowBlur=0});snake.forEach((s,i)=>{const a=1-(i/snake.length)*0.5;ctx.fillStyle=i===0?t.snake:t.snake.replace('rgb','rgba').replace(')',`,${a.toFixed(2)})`);if(i===0){ctx.shadowColor=t.snakeGlow;ctx.shadowBlur=12}ctx.fillRect(s.x*ts+1,s.y*ts+1,ts-2,ts-2);ctx.shadowBlur=0;if(i===0){ctx.fillStyle='#000';const es=Math.max(2,ts/8);ctx.fillRect(s.x*ts+ts*0.25,s.y*ts+ts*0.25,es,es);ctx.fillRect(s.x*ts+ts*0.6,s.y*ts+ts*0.25,es,es)}});eatEffects.forEach(e=>{ctx.fillStyle=e.color;ctx.globalAlpha=e.life;ctx.beginPath();ctx.arc(e.x*ts+ts/2,e.y*ts+ts/2,ts*e.life,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1});ctx.fillStyle=ft.color||t.food;ctx.shadowColor=ft.glow||t.foodGlow;ctx.shadowBlur=18+Math.sin(Date.now()/300)*4;ctx.beginPath();ctx.arc(food.x*ts+ts/2,food.y*ts+ts/2,ts/2-2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font=`${ts-2}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(ft.emoji,food.x*ts+ts/2,food.y*ts+ts/2+1);ctx.restore()}

function dg_(){const t=getTheme();ctx.strokeStyle=t.grid;ctx.lineWidth=0.5;for(let i=0;i<gs;i++){for(let j=0;j<gs;j++){ctx.strokeRect(i*ts,j*ts,ts,ts)}}}

function die_(){ir=false;clearInterval(gl);playDie();saveScore(score,currentLevel+1);checkScoreAchievements(score,gc,currentLevel+1,Math.floor(combo),pf,sc_);if(ig&&score>=50)unlockAchievement('ghost_win');if(score>bs){bs=score;document.getElementById('bestDisplay').innerText=bs}const o=document.getElementById('gameOverlay');o.style.display='flex';document.getElementById('overlayIcon').innerText='💀';document.getElementById('overlayTitle').innerText='انتهت اللعبة!';document.getElementById('overlayMsg').innerText=score>=getRequired()?'🎉 أحسنت!':'حاول مرة أخرى!';document.getElementById('overlayScore').innerText=score;document.getElementById('overlayBtn').innerText='🔄 العب مرة أخرى';document.getElementById('overlayBtn').onclick=startGame}

function tp_(){if(!ir)return;ip=!ip;const o=document.getElementById('gameOverlay');if(ip){o.style.display='flex';document.getElementById('overlayIcon').innerText='⏸️';document.getElementById('overlayTitle').innerText='متوقف';document.getElementById('overlayMsg').innerText='';document.getElementById('overlayScore').innerText=score;document.getElementById('overlayBtn').innerText='▶️ استمرار';document.getElementById('overlayBtn').onclick=tp_}else{o.style.display='none'}}

function resetGame(){if(confirm('إعادة تعيين كل البيانات؟ (النتائج والإنجازات)')){localStorage.removeItem('snake2044_scores');localStorage.removeItem('snake2044_achievements');bs=0;document.getElementById('bestDisplay').innerText='0';showToast('🔄 تم إعادة التعيين')}}

function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

ig_();