let currentCity='Riyadh',currentData=null,isCelsius=true;
const WEATHER_ICONS={Clear:'☀️',Clouds:'☁️',Rain:'🌧️',Drizzle:'🌦️',Thunderstorm:'⛈️',Snow:'❄️',Mist:'🌫️',Fog:'🌫️',Haze:'🌫️',Dust:'🌪️',Sand:'🌪️',Smoke:'🌫️',Tornado:'🌪️',Squall:'💨'};
const WEATHER_BG={Clear:'linear-gradient(180deg,#1a3a5c,#0d2137,#0a1628)',Clouds:'linear-gradient(180deg,#2c3e50,#1a252f,#0a1628)',Rain:'linear-gradient(180deg,#1a2a3a,#121d2a,#0a1628)',Drizzle:'linear-gradient(180deg,#1a2a3a,#121d2a,#0a1628)',Thunderstorm:'linear-gradient(180deg,#0f0f1a,#0a0a12,#050508)',Snow:'linear-gradient(180deg,#2a3a4a,#1a2a3a,#0a1628)',Mist:'linear-gradient(180deg,#1a2a35,#121d28,#0a1628)',Fog:'linear-gradient(180deg,#1a2a35,#121d28,#0a1628)',Haze:'linear-gradient(180deg,#2a2a25,#1a1a18,#0a1628)',Dust:'linear-gradient(180deg,#2a2a20,#1a1a15,#0a1628)'};
function initWeather(){const last=getLastCity();if(last)currentCity=last;fetchWeather(currentCity);renderFavorites()}
async function fetchWeather(city){try{const geoRes=await fetch(`https://api.openweathermap.org/geo/1.0/direct?q=${city}&limit=1&appid=bd5e378503939578c5d3d5c5a6d0b19a`);const geoData=await geoRes.json();if(!geoData.length){showToast('⚠ المدينة غير موجودة');return}const{lat,lon,name,country}=geoData[0];const weatherRes=await fetch(`https://api.openweathermap.org/data/2.5/forecast?lat=${lat}&lon=${lon}&units=metric&appid=bd5e378503939578c5d3d5c5a6d0b19a`);const weatherData=await weatherRes.json();currentData=weatherData;currentCity=city;saveLastCity(city);updateUI(weatherData,name,country);updateHourly(weatherData);updateWeekly(weatherData)}catch(e){console.error(e);generateMockWeather(city);showToast('📡 بيانات محاكاة (غير متصل)')}}
function generateMockWeather(city){const conditions=['Clear','Clouds','Rain'];const c=conditions[Math.floor(city.length%3)];const t=Math.floor(Math.random()*15+20);const data={list:Array.from({length:40},(_,i)=>({dt:Date.now()/1000+i*3600,main:{temp:t+Math.sin(i)*5,humidity:Math.floor(Math.random()*30+40),feels_like:t+Math.sin(i)*3-2,visibility:10000},wind:{speed:Math.random()*20+5},weather:[{main:c,description:'سماء صافية'}],pop:Math.random()})),city:{name:city,country:'🇸🇦'}};currentData=data;updateUI(data,city,'🇸🇦');updateHourly(data);updateWeekly(data)}
function updateUI(data,name,country){const current=data.list[0];const w=current.weather[0];const icon=WEATHER_ICONS[w.main]||'🌈';const bg=WEATHER_BG[w.main]||WEATHER_BG.Clear;document.getElementById('bgSky').style.background=bg;document.getElementById('weatherIcon').innerText=icon;document.getElementById('weatherTemp').innerText=Math.round(current.main.temp)+'°';document.getElementById('weatherDesc').innerText=w.description||'سماء صافية';document.getElementById('cityName').innerText=name+', '+country;document.getElementById('humidity').innerText=current.main.humidity+'%';document.getElementById('windSpeed').innerText=Math.round(current.wind.speed)+' كم/س';document.getElementById('visibility').innerText=(current.main.visibility/1000).toFixed(1)+' كم';document.getElementById('feelsLike').innerText=Math.round(current.main.feels_like)+'°'}
function updateHourly(data){const container=document.getElementById('hourlyForecast');container.innerHTML=data.list.slice(0,8).map(h=>{const t=new Date(h.dt*1000);const time=t.getHours()+':00';const icon=WEATHER_ICONS[h.weather[0].main]||'🌈';const temp=Math.round(h.main.temp)+'°';return`<div class="hourly-item"><div class="hour-time">${time}</div><div class="hour-icon">${icon}</div><div class="hour-temp">${temp}</div></div>`}).join('')}
function updateWeekly(data){const container=document.getElementById('weeklyForecast');const days={};data.list.forEach(h=>{const d=new Date(h.dt*1000).toLocaleDateString('ar-SA',{weekday:'long'});if(!days[d])days[d]={temps:[],icon:h.weather[0].main};days[d].temps.push(h.main.temp)});container.innerHTML=Object.entries(days).slice(0,7).map(([day,info])=>{const min=Math.round(Math.min(...info.temps));const max=Math.round(Math.max(...info.temps));const icon=WEATHER_ICONS[info.icon]||'🌈';return`<div class="weekly-item"><div class="w-day">${day}</div><div class="w-icon">${icon}</div><div class="w-temp">${max}° / ${min}°</div></div>`}).join('')}
function detectLocation(){if(navigator.geolocation){navigator.geolocation.getCurrentPosition(async pos=>{try{const res=await fetch(`https://api.openweathermap.org/geo/1.0/reverse?lat=${pos.coords.latitude}&lon=${pos.coords.longitude}&limit=1&appid=bd5e378503939578c5d3d5c5a6d0b19a`);const data=await res.json();if(data.length){currentCity=data[0].name;fetchWeather(currentCity);showToast('📍 '+currentCity)}}catch(e){showToast('📍 تم تحديد موقعك')}},()=>showToast('⚠ تعذر تحديد الموقع'))}else{showToast('⚠ GPS غير مدعوم')}}
function toggleSearch(){const bar=document.getElementById('searchBar');bar.style.display=bar.style.display==='none'?'flex':'none';if(bar.style.display==='flex')document.getElementById('searchInput').focus()}
function searchCity(){const input=document.getElementById('searchInput');const city=input.value.trim();if(city){fetchWeather(city);document.getElementById('searchBar').style.display='none';input.value=''}}
function addFavoriteCity(){const city=prompt('اسم المدينة:');if(city&&city.trim()){addFavorite(city.trim());renderFavorites();showToast('⭐ تمت الإضافة')}}
function selectFavorite(city){currentCity=city;fetchWeather(city)}
function deleteFavorite(city){removeFavorite(city);renderFavorites();showToast('🗑 تم الحذف')}
function renderFavorites(){const container=document.getElementById('favCities');const favs=getFavorites();if(!favs.length){container.innerHTML='<div class="empty-fav">أضف مدنك المفضلة ⭐</div>';return}container.innerHTML=favs.map(c=>`<div class="fav-chip ${c===currentCity?'active':''}" onclick="selectFavorite('${c}')">📍 ${c}<span class="fav-del" onclick="event.stopPropagation();deleteFavorite('${c}')">✕</span></div>`).join('')}
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}